lang_table = {
    'Chinese': {
        'HI_MSG': '嗨',
        'LOCATION_REQ_TITLE': '位置要求',
        'LOCATION_REQ_TEXT': '請分享你的位置',
        'LOCATION_REQ_HINT': '請輸入 \'嗨\' 來分享你的位置',
        'LOCATION_REQ_LABEL': '分享位置',
        'LOC_REPLY_YOURS': '你的位置:',
        'LOC_REPLY_CLOSEST_BUILDING': '最近的建築物:',
        'LOC_TYPE': '類別:',
        'LOC_COORD': '座標:',
        'LOC_FLOOR': '地下樓層數:',
        'LOC_CAP': '可容納人數:',
        'LOC_AUTH': '轄管分局:',
        'LOC_DIST': '距離:',
        'LOC_KM': '公里',
    },
    'English': {
        'HI_MSG': 'Hi',
        'LOCATION_REQ_TITLE': 'Location Request',
        'LOCATION_REQ_TEXT': 'Please share your location',
        'LOCATION_REQ_HINT': 'Please type \'Hi\' to share your location',
        'LOCATION_REQ_LABEL': 'Share your location',
        'LOC_REPLY_YOURS': 'Your location:',
        'LOC_REPLY_CLOSEST_BUILDING': 'Closest Building:',
        'LOC_TYPE': 'Type:',
        'LOC_COORD': 'Coordinate:',
        'LOC_FLOOR': 'Floors:',
        'LOC_CAP': 'Capacity:',
        'LOC_AUTH': 'Authority:',
        'LOC_DIST': 'Distance:',
        'LOC_KM': 'km',
    }
}